/**
 * Registry of published insights articles
 * Generated by scripts/process-drafts.ts during build
 */

import { readFile } from "fs/promises";
import { join } from "path";
import { existsSync } from "fs";

export interface PublishedArticle {
  slug: string;
  title: string;
  summary: string;
  category: string;
  content: string;
  images?: string[];
  author?: string;
  publishedAt: string;
  date: string;
  readTime: string;
}

const REGISTRY_FILE = join(process.cwd(), "src/lib/insights/registry.json");

let cachedRegistry: PublishedArticle[] | null = null;

export async function getPublishedArticles(): Promise<PublishedArticle[]> {
  if (cachedRegistry) {
    return cachedRegistry;
  }
  
  if (!existsSync(REGISTRY_FILE)) {
    return [];
  }
  
  try {
    const content = await readFile(REGISTRY_FILE, "utf-8");
    cachedRegistry = JSON.parse(content) as PublishedArticle[];
    return cachedRegistry;
  } catch (error) {
    console.error("Error reading insights registry:", error);
    return [];
  }
}

export async function getPublishedArticle(slug: string): Promise<PublishedArticle | null> {
  const articles = await getPublishedArticles();
  return articles.find((a) => a.slug === slug) || null;
}
